### ISSUE TITLE
Make download.sh executable

### ISSUE THREAD

**Issue by RoganGrant** [theislab/2019_Strunz#1]
Very low priority, clearly, but this would avoid having to copy/paste the contents of the sh file or forking

**Comment by lkmklsmn** [comment]
Hi Rogan, I am glad to see you are interested in the data/analysis. You may be one of the first outside people to delve into this code. Pls dont hesitate to ask questions if you get stuck or to point out potential improvements!

**Comment by RoganGrant** [comment]
Thank you for your help! I will be sure to do so.
