### ISSUE TITLE
Dataset Files No Longer Available

### ISSUE THREAD

**Issue by zhongzheng1999** [theislab/2019_Strunz#5]
Hi, I tried to reproduce your script, but the download.sh doesn't seem to work, can you send a new download link?

**Comment by ChrisTzaferis** [comment]
Hi, I faced the same problem with the download.sh script, however by using the link included in the script: https://1drv.ms/f/s!AiwuS6Fz15R0gsgiXtjxJZqr-BDt0A?e=nCnnJ5  (pasting it in a new tab in my browser), I could download the data manually.

**Comment by lkmklsmn** [comment]
Indeed, we just updated the link yesterday. I am glad you got it to download. Thanks for your interest in our data!

**Comment by ChrisTzaferis** [comment]
Thank you very much for updating the link! Congratulations to all the contributors for the very interesting publication and thank you once more for sharing your processed data and scripts, facilitating reproducibility!
